import keyMirror from 'key-mirror';

export default keyMirror({
  LOGIN_REQUEST: null,
  LOGIN_SUCCESS: null,
  LOGIN_FAILURE: null,
  LAUNCH_APP: null,
  ROUTER_FOCUS: null,
  LOGOUT_USER: null,
  EDIT_USER: null,

  ON_RECEIVE_ALERT: null,
  ON_GLOBAL_FIELD_CHANGE: null,

  SAVE_SELECTED_IMAGE: null,
  RESET_SELECTED_IMAGE: null,
  ON_UPLOAD_IMAGE: null,
  UPLOAD_IMAGE_SUCCESS: null,
  UPLOAD_IMAGE_FAILURE: null,
  ON_DELIVERY_FIELD_CHANGE: null,

  ON_CONTRACT_FIELD_CHANGE: null,
  GET_LIST_TRANPORTER_REQUEST: null,
  GET_LIST_TRANPORTER_SUCCESS: null,
  GET_LIST_TRANPORTER_FAILURE: null,

  ON_QUY_TRINH_FIELD_CHANGE: null,
  GET_LIST_QUY_TRINH_REQUEST: null,
  GET_LIST_QUY_TRINH_SUCCESS: null,
  GET_LIST_QUY_TRINH_FAILURE: null
});
